general:
  gateway_name: henrietta
  gateway_location: fcre-catwalk
  gateway_power_mode: ac # "ac" or "battery"
  gateway_maintenance_mode: true # true or false
  data_dir: /data
  apps_dir: /home/ubuntu/miscellaneous
  datalogger_data_dir: datalogger-data
  git_repo: git@github.com:FLARE-forecast/FCRE-data.git
  git_data_branch: fcre-catwalk-data
  git_logs_branch: henrietta-logs

scheduler:
  shutdown_delay_after_reboot: 30 # Shutdown delay after reboot in minutes
  shutdown_time: 00:10 # Exact time for shutdown

startup_notifier:
  log_file: startup-notifier.log
  local_repo_dir: startup-notifier
  git_repo: git@github.com:FLARE-forecast/FCRE-data.git
  git_branch: main

status_monitor:
  log_file: status-monitor.log

ping_monitor:
  log_file_full: ping-monitor-full.log
  log_file_stat: ping-monitor-stat.log

git_push:
  log_file: git-push.log

git_garbage_collector:
  log_file: git-garbage-collector.log

health_checks_io:
  ping_url: https://hc-ping.com/b412fc85-0d1d-45d9-979e-d310038bf44d

reverse_ssh:
  log_file: reverse-ssh.log
  local_port: 60008
  base_port: 61000
  remote_port: 22
  localhost: localhost
  server: 149.165.159.29
  user: ubuntu
  ServerAliveInterval: 30
  ServerAliveCountMax: 3
