general:
  gateway_name: carina
  gateway_location: datalogger-mock
  gateway_power_mode: ac # "ac" or "battery"
  gateway_maintenance_mode: true # true or false
  data_dir: /data
  apps_dir: /home/ubuntu/miscellaneous
  datalogger_data_dir: datalogger-data
  git_repo: git@github.com:FLARE-forecast/miscellaneous.git
  git_data_branch: datalogger-mock-data
  git_logs_branch: carina-logs

scheduler:
  enabled: true
  shutdown_delay_after_reboot: 30 # Shutdown delay after reboot in minutes
  shutdown_time: 00:10 # Exact time for shutdown

startup_notifier:
  enabled: true
  log_file: startup-notifier.log
  local_repo_dir: startup-notifier
  git_repo: git@github.com:FLARE-forecast/miscellaneous.git
  git_branch: startup-notifier

status_monitor:
  enabled: true
  log_file: status-monitor.log

ping_monitor:
  enabled: false
  log_file_full: ping-monitor-full.log
  log_file_stat: ping-monitor-stat.log

git_push:
  enabled: true
  log_file: git-push.log

git_garbage_collector:
  enabled: true
  log_file: git-garbage-collector.log

health_checks_io:
  enabled: true
  ping_url: https://hc-ping.com/63de05f7-b025-4645-8552-b5e0cae48f61

reverse_ssh:
  enabled: false
  log_file: reverse-ssh.log
  local_port: 60002
  base_port: 61000
  remote_port: 22
  localhost: localhost
  server: 149.165.159.29
  user: ubuntu
  ServerAliveInterval: 30
  ServerAliveCountMax: 3

datalogger_mock_data_generator:
  enabled: false
  log_file: datalogger-mock-data-generator.log
  data_file: datalogger-mock-data.csv
  interval: 10 # Frequency of generating data in minutes

network_interface_monitor:
  enabled: false
  interfaces:
  - name: tnc0
    log_file: network-interface-monitor-tnc0.log
  - name: nebula1
    log_file: network-interface-monitor-nebula1.log
