general:
  gateway_name: bita
  gateway_location: datalogger-mock
  gateway_power_mode: ac # "ac" or "battery"
  gateway_maintenance_mode: true # true or false
  data_dir: /data
  apps_dir: /home/ubuntu/miscellaneous
  datalogger_data_dir: datalogger-data
  git_repo: git@github.com:FLARE-forecast/miscellaneous.git
  git_data_branch: datalogger-mock-data-2
  git_logs_branch: carina-logs

scheduler:
  enabled: true
  log_file: scheduler.log
  shutdown_delay_after_reboot: 30 # Shutdown delay after reboot in minutes
  shutdown_time: 00:10 # Exact time for shutdown

startup_notifier:
  enabled: true
  log_file: startup-notifier.log
  local_repo_dir: startup-notifier
  git_repo: git@github.com:FLARE-forecast/miscellaneous.git
  git_branch: startup-notifier

status_monitor:
  enabled: true
  log_file: status-monitor.log

git_push:
  enabled: true
  log_file: git-push.log
  directories:
  - /data/datalogger-mock-data-2
  - /data/bita-logs

git_garbage_collector:
  enabled: true
  log_file: git-garbage-collector.log
  directories:
  - /data/datalogger-mock-data-2
  - /data/bita-logs

health_checks_io:
  enabled: true
  log_file: health-checks-io.log
  ping_url: https://hc-ping.com/bf7a9370-62dc-4460-92cd-3dd8c73653b6
  max_time: 60
  retry: 5

reverse_ssh:
  enabled: true
  log_file: reverse-ssh.log
  local_port: 60012
  base_port: 61000
  remote_port: 22
  localhost: localhost
  server: 149.165.159.29
  user: ubuntu
  ServerAliveInterval: 30
  ServerAliveCountMax: 3

datalogger_mock_data_generator:
  enabled: false
  log_file: datalogger-mock-data-generator.log
  data_file: datalogger-mock-data.csv
  interval: 10 # Frequency of generating data in minutes

network_interface_monitor:
  enabled: false
  log_file: network-interface-monitor.log
  log_rotation_interval: 86400 # Frequency of log rotation in seconds
  interfaces:
  - name: enp2s0
    log_file: enp2s0.log
  - name: nebula1
    log_file: nebula1.log

led_monitor:  # Not working with newer Linux kernels
  enabled: false
  log_file: led-monitor.log
