general:
  log_file: general.log
  gateway_name: norvel
  gateway_location: fcre-metstation
  gateway_power_mode: ac # "ac" or "battery"
  data_dir: /data
  apps_dir: /home/ubuntu/miscellaneous
  datalogger_data_dir: datalogger-data
  git_repo: git@github.com:FLARE-forecast/FCRE-data.git
  git_data_branch: fcre-metstation-data
  git_logs_branch: norvel-logs
  module_toggler_log_file: module-toggler.log

shutdown_scheduler:
  is_enabled: true
  log_file: shutdown-scheduler.log
  post_reboot_delay_minutes: 30 # Delay after reboot before scheduling a shutdown when on battery
  shutdown_time: 00:10 # HH:MM format, the exact time to schedule a shutdown when on AC power

startup_notifier:
  is_enabled: true
  log_file: startup-notifier.log
  local_repo_dir: startup-notifier
  git_repo: git@github.com:FLARE-forecast/FCRE-data.git
  git_branch: main

status_monitor:
  is_enabled: true
  log_file: status-monitor.log

git_push:
  is_enabled: true
  log_file: git-push.log
  directories:
    - /data/fcre-metstation-data
    - /data/norvel-logs

git_garbage_collector:
  is_enabled: true
  log_file: git-garbage-collector.log
  directories:
    - /data/fcre-metstation-data
    - /data/norvel-logs

health_checks_io:
  is_enabled: true
  log_file: health-checks-io.log
  ping_url: https://hc-ping.com/c6767e4f-d6ae-4b8f-adb4-141f03283f8c
  max_time: 60
  retry: 5

reverse_ssh:
  is_enabled: true
  log_file: reverse-ssh.log
  autossh_log_file: autossh.log
  local_port: 60007
  base_port: 61000
  remote_port: 22
  localhost: localhost
  server: 149.165.159.29
  user: ubuntu
  ServerAliveInterval: 30
  ServerAliveCountMax: 3

datalogger_mock_data_generator:
  is_enabled: false
  log_file: datalogger-mock-data-generator.log
  data_file: datalogger-mock-data.csv
  interval: 10 # Frequency of generating data in minutes

network_interface_monitor:
  is_enabled: false
  log_file: network-interface-monitor.log
  log_rotation_interval: 86400 # Frequency of log rotation in seconds
  interfaces:
    - name: tnc0
      log_file_directory: tnc0 # To store .pcap files

led_monitor:  # Not working with newer Linux kernels
  is_enabled: false
  log_file: led-monitor.log

lora_radio:
  is_enabled: true
  log_file: lora-radio.log
  mode: noevio # "evio" or "noevio" or "pendant"
  serial_interface: ttyUSB0
  lora_interface: tnc0
  evio_interface: appCIBR6
  switch_interface: enp1s0
  node_ip: 10.10.101.1/24 # ip/netmask
  switch_ip: 10.10.101.1/24 # ip/netmask, IP address of the gateway on the other side of the LoRa link
  baud_rate: 115200
  mtu: 400 # bytes
  rate: 20 # kbit
  burst: 32 # kbit
  latency: 400 # ms
  ingress_policing_rate: 10 #kbit
  ingress_policing_burst: 10 #kbit

nebula_overlay_network:
  is_enabled: true
  log_file: nebula-overlay-network.log
